development:
  adapter: redis
  url: <%= ENV[ENV['REDIS_ACTION_CABLE']||''] %>

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: dungeon_production
